name: Daily Cron Job

on:
  schedule:
    - cron: '*/5 * * * *' # 매일 자정(UTC) 실행

jobs:
  call-vercel-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to Vercel endpoint
        run: curl -X GET "https://on-off-mix-scraper.vercel.app/api/cron"
